Cert Auth
couchbase/docs-sdk-java pull request #227
Opened 2021-04-16 14:49 UTC by RichardSmedley

DOC-8250

2021-04-19 06:39 UTC, daschl requested changes
Note that this is not certificate authentication! Cert auth is the other way round - where you provide a certificate to the server instead of user/password credentials to authenticate.

Here, we are not dealing with authentication, but the client is accepting the server certificate for the connection (you still have to provide username and password). So this is just "encrypted / tls  connections with the custom certificate the server provides)

2021-04-19 10:45 UTC, RichardSmedley commented
>  ...So this is just "encrypted / tls connections with the custom certificate the server provides)

Oops, thanks for catching that @daschl - fixed now.

2021-04-19 10:47 UTC, daschl commented on modules/devguide/examples/java/src/main/java/com/couchbase/devguide/CloudConnect.java
> +// import com.couchbase.client.core.deps.io.netty.handler.ssl.util.InsecureTrustManagerFactory; // use in testing if you use .trustManagerFactory(InsecureTrustManagerFactory.INSTANCE)) instead of Cer
still nothing to do with cert auth (comment)

2021-04-19 10:48 UTC, daschl commented on modules/devguide/examples/java/src/main/java/com/couchbase/devguide/CloudConnect.java
> +                        // .trustManagerFactory(InsecureTrustManagerFactory.INSTANCE))  // use in testing if you use .trustManagerFactory(InsecureTrustManagerFactory.INSTANCE)) instead of Cert Auth (
same

2021-04-19 10:48 UTC, daschl commented on modules/devguide/examples/java/src/main/java/com/couchbase/devguide/CloudConnect.java
> +                        // .trustManagerFactory(InsecureTrustManagerFactory.INSTANCE))  // use in testing if you use .trustManagerFactory(InsecureTrustManagerFactory.INSTANCE)) instead of Cert Auth (
more accurate would be "used in testing if you want to trust all server certificates  / do not validate them"

2021-04-19 10:49 UTC, daschl commented on modules/hello-world/pages/start-using-sdk.adoc
> +During development, you may wish to use `.securityConfig(SecurityConfig.enableTls(true)` (commented out in the code sample below),
this does not make sense? enable tls is always needed both in dev and prod, I think you wanted to mention the insecure manager?

2021-08-25 20:02 UTC, RichardSmedley commented
Closing as has been done properly elsewhere.

2021-08-25 20:02 UTC, closed without merging