cipher suite choice
couchbase/docs-sdk-java pull request #429
Opened 2024-11-27 16:43 UTC by RichardSmedley

DOC-12599

2025-02-06 00:10 UTC, dnault requested changes
Thanks for this!

2025-02-06 00:10 UTC, dnault commented on modules/howtos/pages/managing-connections.adoc
> +/opt/couchbase/bin/couchbase-cli setting-security -c localhost -u Administrator -p password –get
`–get` should be `--get` (somewhere along the line, the two dashes got mangled into an en dash)

2025-02-06 00:10 UTC, dnault commented on modules/howtos/pages/managing-connections.adoc
> +[source.console]
Should that dot be a comma? Like `[source,console]`

2025-02-06 00:10 UTC, dnault commented on modules/howtos/pages/managing-connections.adoc
> +If you are on a version of TLS that allows a cipher suite weaker than your latest security policies allow,
Suggestion:

> If your organization's security policy requires using specific TLS cipher suites,

2025-02-06 00:10 UTC, dnault commented on modules/howtos/pages/managing-connections.adoc
> +link:++https://docs.couchbase.com/sdk-api/couchbase-core-io/com/couchbase/client/core/env/SecurityConfig.Builder.html#ciphers(java.util.List++[`SecurityConfig.Builder (ciphers(List`].
Maybe style the label like this?
```
[the `security.ciphers` client setting]
```

2025-02-06 00:10 UTC, dnault commented on modules/howtos/pages/managing-connections.adoc
> +----
Most folks who need to specify cipher suite will also want to force TLS 1.3. One way to do that is to require a cipher suite introduced in TLS 1.3.

Maybe format this a bit differently, and limit to TLS 1.3 cipher suites that the JVM and all Couchbase services support?

```
Cluster cluster = Cluster.connect(
  connectionString,
  ClusterOptions.clusterOptions(username, password)
    .environment(env -> env
      .securityConfig(sec -> sec
        .ciphers(List.of(
          // TLS 1.3 cipher suites supported by
          // Java and Couchbase Server.
          "TLS_AES_128_GCM_SHA256",
          "TLS_AES_256_GCM_SHA384"
        )))));
  }
}```

2026-01-08 11:22 UTC, RichardSmedley commented
Closing in favour of https://github.com/couchbase/docs-sdk-java/pull/470 against the current dotminor's docs.

2026-01-08 11:22 UTC, closed without merging